apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: zrtcnacos
  labels:
    app: nacos
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: nacos
  ports:
  - port: 8848
    name: client
    targetPort: 8848
  - port: 9848
    name: raft
    targetPort: 9848
  - port: 9849
    name: raft-election
    targetPort: 9849
---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: zrtcnacos
  labels:
    app: nacos
spec:
  type: ClusterIP
  selector:
    app: nacos
  ports:
  - port: 8848
    name: client
    targetPort: 8848
  - port: 9848
    name: raft
    targetPort: 9848
